### ISSUE TITLE
Rename blk variables?

### ISSUE THREAD

**Issue by IvanMartinez** [antoniomo/bloque#1]
Could the code use variable names that make more obvious what is a `BloQue*` and what is a `BlockT`?:
- I find the use of `blk` for `*BloQue` at the beginning of the code misleading. It's also inconsistent with the use of the same name for `BlockT` in line 180. I would prefer something that doesn't omit the queue condition, like `bq` or `blq`.
- I would also prefer that the `BloQue*` receiver wasn't just `b` and made the queue condition more obvious, again `bq` or something like that.

**Comment by antoniomo** [comment]
Hi,

This repo is in maintenance mode until (or if) I rewrite it for any reason. So unless it's a bug, feature request, or the like, I won't make changes, sorry!
